# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# What combinations to test
environment:
  matrix:
    - nodejs_version: "0.10"
      platform: x86
    - nodejs_version: "0.10"
      platform: x64
    - nodejs_version: "0.12"
      platform: x86
    - nodejs_version: "0.12"
      platform: x64
    - nodejs_version: "4"
      platform: x86
    - nodejs_version: "4"
      platform: x64
    - nodejs_version: "5"
      platform: x86
    - nodejs_version: "5"
      platform: x64
    - nodejs_version: "6"
      platform: x86
    - nodejs_version: "6"
      platform: x64

install:
  # work around an issue with node-pre-gyp and node 4x
  # package.json has no certificates in it so we're cool
  # https://github.com/mapbox/node-pre-gyp/issues/209
  - IF %nodejs_version% EQU 4 npm config set -g cafile=package.json
  - IF %nodejs_version% EQU 4 npm config set -g strict-ssl=false

  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% LSS 1 npm -g install npm
  - IF %nodejs_version% LSS 1 set PATH=%APPDATA%\npm;%PATH%
  - npm install
  # - IF %nodejs_version% EQU 0.8 npm install
  # - IF %nodejs_version% NEQ 0.8 npm install --msvs_version=2013

build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - npm ls
  - npm test
