# https://docs.travis-ci.com/user/trusty-ci-environment
sudo: required
dist: trusty

os:
  - linux
  - osx
language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- '6'
script:
  - uname -a
  - npm run lint
  - npm test
